// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RagBasedChatbot.Data;

#nullable disable

namespace RagBasedChatbot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RagBasedChatbot.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("AnswerMessage")
                        .HasColumnType("text");

                    b.Property<string>("QuestionMessage")
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("RagBasedChatbot.Models.User", b =>
                {
                    b.Property<string>("cinsiyet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kullanici_adi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("soyisim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
